"""empty message

Revision ID: 375ce2089885
Revises: 47c3b33affe8
Create Date: 2020-07-23 15:13:38.045111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375ce2089885'
down_revision = '47c3b33affe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'todos', ['user_id'])
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'todos', type_='unique')
    # ### end Alembic commands ###
