"""empty message

Revision ID: 84be832549d0
Revises: 375ce2089885
Create Date: 2020-07-23 15:14:35.597742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84be832549d0'
down_revision = '375ce2089885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('todos', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('todos', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('todos', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
